import { AuthAPI } from "../../../api";
export default {
    namespaced: true,
    state: {
        list:[
            {
                id:1,
                name:"杂货铺管理",
                icon:"icon-groceries",
                second:[
                    {
                        id:2,
                        name:"待审核",
                        url:"groceries",
                    },
                    {
                        id:3,
                        name:"审核通过",
                        url:"check",
                    },
                    {
                        id:4,
                        name:"审核未通过",
                        url:"check-not",
                    },
                    {
                        id:5,
                        name:"待认证",
                        url:"await",
                    }
                ]
            },
            {
                id:6,
                name:"供应商管理",
                url:"",
                icon:"icon-supplier",
                second:[
                    {
                        id:7,
                        name:"待审核",
                        url:"",
                    },
                    {
                        id:8,
                        name:"审核通过",
                        url:"",
                    },
                    {
                        id:9,
                        name:"审核未通过",
                        url:"",
                    }
                ]
            },
            {
                id:10,
                name:"选品库",
                url:"",
                icon:"icon-electoral",
                second:[
                    {
                        id:11,
                        name:"待入库商品管理",
                        url:"",
                    },
                    {
                        id:12,
                        name:"商品管理",
                        url:"",
                    },
                    {
                        id:13,
                        name:"类目管理",
                        url:"",
                        icon:"icon-point",
                        second:[
                            {
                                id:14,
                                name:"后台类目属性管理",
                                url:"",
                            },
                            {
                                id:15,
                                name:"前台类目",
                                url:"",
                            },
                            {
                                id:16,
                                name:"后台类目",
                                url:"",
                            },
                            {
                                id:17,
                                name:"前后台类目映射表",
                                url:"",
                            }
                        ]
                    },
                    {
                        id:18,
                        name:"品牌管理",
                        url:"",
                        icon:"icon-point",
                        second:[
                            {
                                id:19,
                                name:"品牌管理",
                                url:"",
                            },
                            {
                                id:20,
                                name:"品牌系列管理",
                                url:"",
                            }
                        ]
                    },
                    {
                        id:21,
                        name:"单位管理",
                        url:"",
                    },
                ]
            },
            {
                id:22,
                name:"供应商商品管理",
                url:"",
                icon:"icon-commodity",
                second:[
                    {
                        id:23,
                        name:"商品管理",
                        url:"",
                    }
                ]
            },
            {
                id:24,
                name:"订单管理",
                url:"",
                icon:"icon-order",
                second:[
                    {
                        id:25,
                        name:"订单列表",
                        url:"",
                    }
                ]
            },
            {
                id:26,
                name:"商品信息更新",
                url:"",
                icon:"icon-commodity-info",
                second:[
                    {
                        id:27,
                        name:"抓取匹配列表",
                        url:"",
                    },
                    {
                        id:28,
                        name:"待匹配列表",
                        url:"",
                    },
                    {
                        id:29,
                        name:"已匹配列表",
                        url:"",
                    }
                ]
            },
            {
                id:30,
                name:"商品合并自检",
                url:"",
                icon:"icon-merge",
                second:[
                    {
                        id:31,
                        name:"待审核",
                        url:"",
                    }
                ]
            },
            {
                id:32,
                name:"神批录入",
                url:"",
                icon:"icon-entry",
                second:[
                    {
                        id:33,
                        name:"审核列表",
                        url:"",
                    }
                ]
            },
            {
                id:34,
                name:"日志列表",
                url:"",
                icon:"icon-logs"
            },
            {
                id:35,
                name:"常用工具",
                url:"",
                icon:"icon-tools",
                second:[
                    {
                        id:36,
                        name:"神策数据",
                        url:"",
                    }
                ]
            }
        ]
    },
    mutations: {
        getCode(state) {
            if(process.env.NODE_ENV !== 'development'){
                AuthAPI.login().then((res) => {
                    console.log(res);
                    if (res.data.err === '0') {
                        const cs = res.data.ret.key;
                        if (cs) {
                            this.canarr = cs.split('');
                        } else {
                            this.$router.replace({ name: 'unAuth' });
                        }
                    } else {
                        this.$router.replace({ name: 'unAuth' });
                    }
                }).catch(() => {
                    this.$router.replace({ name: 'unAuth' });
                });
            }else{

            }
        }
    }
}